# Generated by Django 4.2.3 on 2023-07-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiV1", "0002_remove_customuser_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="login",
            new_name="username",
        ),
    ]
