# Generated by Django 4.2.3 on 2023-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiV1", "0003_rename_login_customuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="data_joined",
            new_name="date_joined",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
