# Generated by Django 4.2.3 on 2023-07-16 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiV1", "0005_product_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
