# Generated by Django 4.2.3 on 2023-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiV1", "0006_order_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
